# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='n_type',
            field=models.CharField(choices=[('LIKE', 'LIKE'), ('ANSWER', 'ANSWER'), ('FOLLOW', 'FOLLOW')], max_length=20, null=True),
        ),
    ]
